---
alias: Sync Living Room lights to wall switch
trigger:
  platform: state
  entity_id: light.living_room_ceiling_light
  to:
action:
  service: light.turn_{{ trigger.to_state.state }}
  entity_id:
    - light.living_room_huego_left
    - light.living_room_huego_right
    - light.living_room_christmas_tree
    - light.living_room_wled_shell
