---
alias: Turn on living room light when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.living_room_sensor_motion
  to: "on"
condition:
  condition: time
  after: "08:00:00"
  before: "22:00:00"
action:
  service: light.turn_on
  entity_id:
    - light.living_room_ceiling_light
    - light.living_room_huego_left
    - light.living_room_huego_right
    - light.living_room_christmas_tree
    - light.living_room_wled_shell
