---
alias: Turn off living room light when there is no movement
trigger:
  - platform: state
    entity_id: sensor.living_room_motion
    to: "off"
    for:
      minutes: 30
  - platform: state
    entity_id: sensor.living_room_motion
    to: "off"
    for:
      minutes: 10
condition:
  condition: or
  conditions:
    - condition: and
      conditions:
        - condition: time
          after: "05:30:00"
          before: "23:00:00"
        - condition: state
          entity_id: sensor.living_room_motion
          to: "off"
          for:
            minutes: 30
    - condition: and
      conditions:
        - condition: time
          after: "23:59:00"
          before: "05:30:00"
        - condition: state
          entity_id: sensor.living_room_motion
          to: "off"
          for:
            minutes: 10
action:
  service: light.turn_off
  entity_id:
    - light.living_room_ceiling
    - light.living_room_huego_left
    - light.living_room_huego_right
