---
alias: Living Room | Motion | Evening | Light Off
trigger:
  platform: state
  entity_id: binary_sensor.living_room_sensor_motion
  to: "off"
  for:
    minutes: 15
condition:
  condition: time
  after: "23:00:00"
  before: "05:30:00"
action:
  service: light.turn_off
  entity_id:
    - light.living_room_ceiling_light
    - light.living_room_huego_left
    - light.living_room_huego_right
