---
alias: Everyone left the living room
trigger:
  - platform: state
    entity_id: sensor.rich_iphone
    from: living_room
    for: 00:05:00
  - platform: state
    entity_id: sensor.farida_iphone
    from: living_room
    for: 00:05:00
  - platform: state
    entity_id: sensor.rich_watch
    from: living_room
    for: 00:05:00
condition:
  condition: not
  conditions:
    - condition: state
      entity_id: sensor.rich_iphone
      state: living_room
    - condition: state
      entity_id: sensor.farida_iphone
      state: living_room
    - condition: state
      entity_id: sensor.rich_watch
      state: living_room
action:
  service: light.turn_off
  entity_id:
    - light.living_room_ceiling_light
    - light.living_room_huego_left
    - light.living_room_huego_right
    - light.living_room_christmas_tree
    - light.living_room_wled_shell
