---
alias: Turn on kitchen light when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion_occupancy
  to: "on"
action:
  service: light.turn_on
  entity_id: light.kitchen_ceiling
