---
alias: Turn off kitchen light when there is no movement
trigger:
  platform: state
  entity_id: sensor.kitchen_motion
  to: "off"
  for:
    minutes: 15

condition:
  - condition: and
    conditions:
      - condition: time
        after: "07:00:00"
        before: "23:00:00"
      - condition: state
        entity_id: sensor.kitchen_motion
        to: "off"
        for:
          minutes: 15

action:
  service: light.turn_off
  entity_id: light.kitchen_ceiling
