---
alias: Kitchen | Motion | Evening | Light Off
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion_occupancy
  to: "off"
  for:
    minutes: 3
condition:
  condition: time
  after: "23:00:00"
  before: "07:00:00"

action:
  service: light.turn_off
  entity_id: light.kitchen_ceiling
