---
alias: Turn off kitchen light when there is no movement
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion_occupancy
  to: "off"
  for:
    minutes: 15
condition:
  condition: time
  after: "7:00:00"
  before: "23:00:00"
action:
  service: light.turn_off
  entity_id: light.kitchen_ceiling
