alias: Farida's Office Heater Off
trigger:
  platform: time_pattern
  minutes: "/5"
condition:
  - condition: time
    after: "16:30:00"
    before: "09:30:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  service: climate.set_temperature
  entity_id: climate.farida_office_thermostat
  data:
    temperature: 16
